web/config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :cities
  resources :recyclers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recyclers#index"
end

web/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

web/app/models/category.rb
class Category < ApplicationRecord
  has_many :recycler_categories
  has_many :recyclers, through: :recycler_categories
end

web/app/models/city.rb
class City < ApplicationRecord
end

web/app/models/recycler.rb
class Recycler < ApplicationRecord
  belongs_to :city
  has_many :recycler_categories
  has_many :categories, through: :recycler_categories
end

web/app/models/recycler_category.rb
class RecyclerCategory < ApplicationRecord
  belongs_to :recycler
  belongs_to :category
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

web/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.includes(:recycler_categories)
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

web/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: %i[ show edit update destroy ]

  # GET /cities or /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1 or /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities or /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to city_url(@city), notice: "City was successfully created." }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1 or /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to city_url(@city), notice: "City was successfully updated." }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1 or /cities/1.json
  def destroy
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url, notice: "City was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def city_params
      params.require(:city).permit(:name)
    end
end

web/app/controllers/recyclers_controller.rb
class RecyclersController < ApplicationController
  before_action :set_recycler, only: %i[ show edit update destroy ]

  # GET /recyclers or /recyclers.json
  def index
    @q = Recycler.ransack(params[:q])
    @recyclers = @q.result(distinct: true).includes(:categories)

    lon = @recyclers.map(&:lon).compact
    lat = @recyclers.map(&:lat).compact

    @center = { lon: lon.reduce(:+) / lon.size, lat: lat.reduce(:+) / lat.size }
  end

  # GET /recyclers/1 or /recyclers/1.json
  def show
  end

  # GET /recyclers/new
  def new
    @recycler = Recycler.new
  end

  # GET /recyclers/1/edit
  def edit
  end

  # POST /recyclers or /recyclers.json
  def create
    @recycler = Recycler.new(recycler_params)

    respond_to do |format|
      if @recycler.save
        format.html { redirect_to recycler_url(@recycler), notice: "Recycler was successfully created." }
        format.json { render :show, status: :created, location: @recycler }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recycler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recyclers/1 or /recyclers/1.json
  def update
    respond_to do |format|
      if @recycler.update(recycler_params)
        format.html { redirect_to recycler_url(@recycler), notice: "Recycler was successfully updated." }
        format.json { render :show, status: :ok, location: @recycler }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recycler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recyclers/1 or /recyclers/1.json
  def destroy
    @recycler.destroy

    respond_to do |format|
      format.html { redirect_to recyclers_url, notice: "Recycler was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recycler
      @recycler = Recycler.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recycler_params
      params.require(:recycler).permit(:name, :description, :phone, :email, :city_id, :address, :url, :lon, :lat, category_ids: [])
    end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/categories_helper.rb
module CategoriesHelper
end

web/app/helpers/cities_helper.rb
module CitiesHelper
end

web/app/helpers/recyclers_helper.rb
module RecyclersHelper
end

web/app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <h1><%= category.name %></h1>
</div>

web/app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

web/app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

web/app/views/categories/index.html.haml
%div{ style: 'float: right' }
  = link_to 'Добавить категорию', new_category_path

%h1 Категории

#categories
  - @categories.each do |category|
    %li= link_to "#{category.name} (#{category.recycler_categories.count})", category

web/app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

web/app/views/categories/show.html.haml
= render @category

%h2 Пункты приёма

%ul
  - @category.recyclers.each do |recycler|
    %li= link_to recycler.description, recycler


%div
  = link_to "Edit this category", edit_category_path(@category)
  |
  \#{link_to "Back to categories", categories_path}
  
  \#{button_to "Destroy this category", @category, method: :delete}

web/app/views/cities/_city.html.erb
<div id="<%= dom_id city %>">
  <p>
    <strong>Name:</strong>
    <%= city.name %>
  </p>

</div>

web/app/views/cities/_form.html.erb
<%= form_with(model: city) do |form| %>
  <% if city.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
        <% city.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

web/app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Show this city", @city %> |
  <%= link_to "Back to cities", cities_path %>
</div>

web/app/views/cities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cities</h1>

<div id="cities">
  <% @cities.each do |city| %>
    <%= render city %>
    <p>
      <%= link_to "Show this city", city %>
    </p>
  <% end %>
</div>

<%= link_to "New city", new_city_path %>

web/app/views/cities/new.html.erb
<h1>New city</h1>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Back to cities", cities_path %>
</div>

web/app/views/cities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @city %>

<div>
  <%= link_to "Edit this city", edit_city_path(@city) %> |
  <%= link_to "Back to cities", cities_path %>

  <%= button_to "Destroy this city", @city, method: :delete %>
</div>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Greenbot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src='https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.js'></script>
    <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-language/v1.0.0/mapbox-gl-language.js'></script>
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.css' rel='stylesheet' />
  </head>

  <body>
    <%= link_to 'Пункты приёма', recyclers_path %>
    <%= link_to 'Категории', categories_path %>
    <hr />
    <%= yield %>
  </body>
</html>

web/app/views/recyclers/_form.html.haml
= simple_form_for recycler do |f|
  = f.input :name
  = f.input :description
  = f.association :city
  = f.input :address
  = f.input :phone, as: :tel
  = f.input :email, as: :email
  = f.input :url, as: :url
  = f.input :lon
  = f.input :lat

  %h2 Категории
  = f.association :categories, as: :check_boxes

  = f.submit

web/app/views/recyclers/_js.html.erb
<script>
  mapboxgl.accessToken = 'pk.eyJ1IjoieXVyeWtvdGx5YXJvdiIsImEiOiJja2M5NGM0djYwOTFqMnhsa2J4ZW1vbHBzIn0.475kMy3wnzKILq9XbTcXig';

  var map = new mapboxgl.Map({
    container: 'map', // container ID
    style: 'mapbox://styles/mapbox/streets-v11', // style URL
    center: [<%= @center[:lon] %>, <%= @center[:lat] %>],
    zoom: 12 // starting zoom
  });

  if (mapboxgl.getRTLTextPluginStatus() === 'unavailable') {
    mapboxgl.setRTLTextPlugin('https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.2.3/mapbox-gl-rtl-text.js');
  }

  map.addControl(new MapboxLanguage({
    defaultLanguage: 'ru'
  }));

  <% @recyclers.each do |recycler| %>
    var popup_<%= recycler.id %> = new mapboxgl.Popup({ offset: 25 }).setHTML(
      '<h3><%= recycler.name&.html_safe %></h3>' +
      '<p><%= recycler.address %></p>' + 
      '<ul><%= recycler.categories.map { |c| "<li>#{link_to c.name, c}</li>" }.join("").html_safe %></ul>'
    );
 
    var marker_<%= recycler.id %> = new mapboxgl.Marker()
      .setLngLat([<%= recycler.lon %>, <%= recycler.lat %>])
      .setPopup(popup_<%= recycler.id %>) 
      .addTo(map);
  <% end %>
</script>

web/app/views/recyclers/_recycler.html.haml
%div{:id => "#{dom_id recycler}"}
  %h1= recycler.name

  = recycler.description

  %p
    %strong Координаты:
    = recycler.lat
    ,
    \#{recycler.lon}
  %p
    %strong Город:
    = link_to recycler.city.name, recycler.city
  %p
    %strong Адрес:
    = recycler.address
  %p
    %strong Телефон:
    = recycler.phone
  %p
    %strong E-mail:
    = recycler.email
  %p
    %strong URL:
    - if recycler.url
      = link_to recycler.url, recycler.url, target: '_blank'

web/app/views/recyclers/edit.html.erb
<h1>Editing recycler</h1>

<%= render "form", recycler: @recycler %>

<br>

<div>
  <%= link_to "Show this recycler", @recycler %> |
  <%= link_to "Back to recyclers", recyclers_path %>
</div>

web/app/views/recyclers/index.html.haml
%div{:style => "float:right"}
  = link_to "Добавить пункт приёма", new_recycler_path

%h1 Пункты приёма

Категории:
= search_form_for @q do |f|
  - Category.all.each do |category|
    = f.check_box :recycler_categories_category_id_in, {multiple: true}, category.id , nil
    = category.name
  = f.submit 'Показать'

#map{:style => "height: 800px;"}
  = render 'js'

%table#recyclers
  - @recyclers.each do |recycler|
    %h3
      = link_to recycler.name, recycler
      %small= recycler.categories.map { |c| link_to c.name, c }.join(', ').html_safe
    %span{ style: 'color: #444;'}= recycler.address

web/app/views/recyclers/new.html.erb
<h1>New recycler</h1>

<%= render "form", recycler: @recycler %>

<br>

<div>
  <%= link_to "Back to recyclers", recyclers_path %>
</div>

web/app/views/recyclers/show.html.haml
= render @recycler

%h2 Категории

%ul
  - @recycler.categories.each do |cagegory|
    %li= link_to cagegory.name, cagegory

%div
  = link_to "Edit this recycler", edit_recycler_path(@recycler)
  |
  \#{link_to "Back to recyclers", recyclers_path}
  
  \#{button_to "Destroy this recycler", @recycler, method: :delete}